language: node_js

node_js:
  - node
  - "6"
  - "4"

script: npm run cover -- --report lcovonly

after_success:
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
  - rm -rf ./coverage
